#!/bin/sh

set -eu	

files="tinyxml2.h tinyxml2.cpp"
baseurl="https://raw.github.com/leethomason/tinyxml2/master/"

for file in $files; do
    echo "Fetching $file"
    curl -L -o "$(dirname "$0")/$file" "$baseurl/$file"
done
