#!/bin/sh

set -eu

files=" LICENSE_1_0.txt integer_seq.h"
baseurl="https://gitorious.org/redistd/integer_seq/raw/"

for file in $files; do
    echo "Fetching $file"
    curl -L -o "$(dirname "$0")/$file" "$baseurl/$file"
done
